# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [78]:
#Write your code here
import numpy as np
import pandas as pd
df_data= pd.read_csv("Purchase_Data.csv")

In [79]:
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [80]:
#Write your code here
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

Slice the first two columns using .loc and store the result in a variable called result_1.

In [81]:
#Write you code here
result_1 = df_data.loc[:,["invoice_number","product_id"]]
result_1

      invoice_number  product_id
0       2.020000e+11     7000300
1       2.020000e+11     7070884
2       2.020000e+11     7070884
3       2.020000e+11     7070891
4       2.020000e+11     7090363
...              ...         ...
5377    2.020000e+11     7308017
5378    2.020000e+11     7070891
5379    2.020000e+11     7071096
5380    2.020000e+11    15000231
5381    2.020000e+11    23030206

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [82]:
#Write you code here
result_2 = df_data.loc[0:1,:]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [83]:
#Write your code here
result_3 = df_data.iloc[0:4,0:5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [84]:
#Write your code here
result_4 = df_data.iloc[[0,4,6],[1,6]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [85]:
num_rows = df_data.shape[0]
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [86]:
#Write your code here
last_row =df_data.iloc[[5381],:]
last_row

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [87]:
#Write your code here
avg_price = df_data['price'].mean()
print (avg_price)

3.1920522110741363

In [88]:
max_price = df_data['price'].max()
print(max_price)

6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [89]:
#Write you code here
avgPriceAndnumOfitems =df_data[['price','num_item']].mean()
avgPriceAndnumOfitems

price       3.192052
num_item    1.298309
dtype: float64

Create a column called "total", which is the product of the price and num_item columns.

In [90]:
#Write your code here
df_data["total"]=df_data["price"]*df_data["num_item"]

In [91]:
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [92]:
#Write your code here
df_data['price'].nlargest(3).mean()

np.float64(6.003333333333333)

How many different products are there?

In [93]:
#Write your code here
df_data.nunique()

invoice_number       1
invoice_time      3502
store_id             5
product_id          53
category_id          7
num_item            15
price               31
total               57
dtype: int64

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [94]:
#Write your code here
df_data.describe()

,invoice_number,product_id,category_id,num_item,price,total
count,5.382000e+03,5.382000e+03,5382.000000,5382.000000,5382.000000,5382.000000
mean,2.020000e+11,8.740911e+06,115465.616499,1.298309,3.192052,3.931808
std,0.000000e+00,5.048294e+06,65448.435316,2.168725,1.652007,5.820520
min,2.020000e+11,7.000034e+06,70101.000000,0.500000,0.000000,0.000000
25%,2.020000e+11,7.070884e+06,70201.000000,1.000000,2.000000,2.000000
50%,2.020000e+11,7.071096e+06,70401.000000,1.000000,2.500000,3.000000
75%,2.020000e+11,7.090592e+06,210101.000000,1.000000,5.000000,5.000000
max,2.020000e+11,3.000077e+07,210301.000000,116.000000,6.010000,348.000000

In [95]:
diff = df_data['total'].mean() - df_data['total'].median()
print(diff)

0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [96]:
#Write your code here
df_data.drop(columns=['total'])

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [97]:
#Write your code here
df_data["invoice_time"] = pd.to_datetime(df_data["invoice_time"])

C:\Users\Al forsan\AppData\Local\Temp\ipykernel_14068\1973541523.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data["invoice_time"] = pd.to_datetime(df_data["invoice_time"])

In [98]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   datetime64[ns]
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
 7   total           5382 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 336.5+ KB

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [99]:
#Write your code here
df_data["DOW"]= df_data["invoice_time"].dt.day_name()

In [100]:
df_data["Month"]= df_data["invoice_time"].dt.month_name()

In [101]:
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,2.0,Wednesday,July
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,Wednesday,July
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,Wednesday,July
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,6.0,Wednesday,July
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,6.0,Wednesday,July

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [102]:
num_purchases_wed =df_data.value_counts(["DOW"])["Wednesday"]
num_purchases_wed

np.int64(959)

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [103]:
#Write your code here
df = pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [104]:
#Write your code here
df.rename(columns={"Name":"Passenger_Name","Ticket":"Ticket_Number"},inplace=True)
df.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Number,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [105]:
#Write your code here
df = df.set_index("PassengerId")

In [106]:
df.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Number,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [107]:
#Write your code here
df.loc[[896],["Passenger_Name"]]

                                           Passenger_Name
PassengerId
896          Hirvonen, Mrs. Alexander (Helga E Lindqvist)

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [108]:
#Write your code here
df.reset_index()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Number,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [109]:
#Write you code here
df["Age"].isnull().sum()

np.int64(86)

Compute the avg age of passengers ignoring the missing data.

In [110]:
#Write your code here
df["Age"].mean()

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [111]:
#Write your code here
df["Age"].fillna(df["Age"].mean())

PassengerId
892     34.50000
893     47.00000
894     62.00000
895     27.00000
896     22.00000
          ...
1305    30.27259
1306    39.00000
1307    38.50000
1308    30.27259
1309    30.27259
Name: Age, Length: 418, dtype: float64

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [112]:
#Write your code here
df["Age"].nlargest(5).mean()

np.float64(67.0)